language: node_js
node_js:
  - 10  # Maintenance LTS

stages:
  - lint
  - test
  - build
jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      script: skip
    - stage: build
      script: npm run build
